### PR TITLE
Implementation of iso19139.rndt for gn 3.x 

### PR DESCRIPTION
**Pull request by davidegiacomelli**
Implementation of gn3.x version of the plugin, based on iso19139 standard version   and old version of iso19139.rndt version implemented for geonetwork 2.10
The "Provincia Autonoma di Trento" has financed the creation of the geonetwork 3.x plugin for the compilation of metadata according to the rndt standard.
The code is donated to the geonetwork community for its public usage.

### CODE REVIEW

**Comment by etj** [comment]
- Please remove all unneded files, such as the `/target` directory 
- Pls follow the maven conventions, i.e:
   - `java/` dir should be inside `main/src/`
   - `resources/` dir should be inside `main/src/`
- Many `extract-*` files are missing

Please compare your directory hierarchy with the iso19139 schema and check for all the missing files.

**Comment by davidegiacomelli** [comment]
I've finished the transposition of the indications you gave me last time.
They are pushed to master branch.
Waiting for your reply,
thanks

**Comment by etj** [comment]
Hi @davidegiacomelli 
how did you deploy/run the plugin?

I build it using maven, and included the generated jar file into the lib directory.
Tomcat choked with a 
```
java.lang.ClassNotFoundException: org.fao.geonet.schema.iso19139rndt.ISO19139RNDTSchemaPlugin
```
because you removed the java file, but the spring application context file is still referring to it.

**Comment by etj** [comment]
@davidegiacomelli  I still have problems installing the plugin. 
I tried both the standard ways (deploy the jar in the war file, add the rndt module in the schemas module and rebuild) but neither is working: i.e. I can't see the rndt standard in the list.
How did you deploy the plugin?
Which geonetwork versions did you test?  I tried 3.4.5.

**Comment by davidegiacomelli** [comment]
Hi Emanuele
I deploy coping  plugin folder in schemas directory of core-geonetwork project,
Then adding reference in schemas/pom.xml
And in web/pom.xml file  as I read here:

https://geonetwork-opensource.org/manuals/trunk/en/customizing-application/implementing-a-schema-plugin.html?highlight=Preparation

The version I tested is 3.4.4

Davide Giacomelli, M. Eng.
Senior Engineer – PM, GIS & HelpDesk Lab
Trilogis srl
P.IVA-C.F. 019769202221
T+39 0461 17.88.032 | F+39 0461 17.88.033
www.trilogis.it<http://www.trilogis.it/> | info@trilogis.it<mailto:info@trilogis.it>
Legal Address: Via G.B. Trener, 10 - 38121 Trento (TN) - Italy
Headquarters: Via Fortunato Zeni, 8 - 38068 Rovereto (TN) - Italy

Da: Emanuele Tajariol <notifications@github.com>
Inviato: lunedì 4 febbraio 2019 17:05
A: metadata101/iso19139.rndt <iso19139.rndt@noreply.github.com>
Cc: Davide Giacomelli <Davide.Giacomelli@trilogis.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [metadata101/iso19139.rndt] Implementation of iso19139.rndt for gn 3.x (#1)


@davidegiacomelli<https://github.com/davidegiacomelli> I still have problems installing the plugin.
I tried both the standard ways (deploy the jar in the war file, add the rndt module in the schemas module and rebuild) but neither is working: i.e. I can't see the rndt standard in the list.
How did you deploy the plugin?
Which geonetwork versions did you test? I tried 3.4.5.

**Pull request merged**
